In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_csv("googleplaystore.csv")

In [3]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [4]:
df["Category"][(df["Category"].apply(lambda x: x== "1.9" ))]

10472    1.9
Name: Category, dtype: object

In [5]:
df[df["Category"] == "1.9"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [6]:
df.drop(10472, axis =0, inplace = True)

In [7]:
df.loc[10469 : 10478]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10469,TownWiFi | Wi-Fi Everywhere,COMMUNICATION,3.9,2372,58M,"500,000+",Free,0,Everyone,Communication,"August 2, 2018",4.2.1,4.2 and up
10470,Jazz Wi-Fi,COMMUNICATION,3.4,49,4.0M,"10,000+",Free,0,Everyone,Communication,"February 10, 2017",0.1,2.3 and up
10471,Xposed Wi-Fi-Pwd,PERSONALIZATION,3.5,1042,404k,"100,000+",Free,0,Everyone,Personalization,"August 5, 2014",3.0.0,4.0.3 and up
10473,osmino Wi-Fi: free WiFi,TOOLS,4.2,134203,4.1M,"10,000,000+",Free,0,Everyone,Tools,"August 7, 2018",6.06.14,4.4 and up
10474,Sat-Fi Voice,COMMUNICATION,3.4,37,14M,"1,000+",Free,0,Everyone,Communication,"November 21, 2014",2.2.1.5,2.2 and up
10475,Wi-Fi Visualizer,TOOLS,3.9,132,2.6M,"50,000+",Free,0,Everyone,Tools,"May 17, 2017",0.0.9,2.3 and up
10476,Lennox iComfort Wi-Fi,LIFESTYLE,3.0,552,7.6M,"50,000+",Free,0,Everyone,Lifestyle,"March 22, 2017",2.0.15,2.3.3 and up
10477,Sci-Fi Sounds and Ringtones,PERSONALIZATION,3.6,128,11M,"10,000+",Free,0,Everyone,Personalization,"September 27, 2017",4.0,4.0 and up
10478,Sci Fi Sounds,FAMILY,3.2,4,8.0M,"1,000+",Free,0,Everyone,Entertainment,"November 2, 2017",1.0,4.0 and up

# When axis = 1 should be used and when axis = 0

In [8]:
df.drop("App" , axis = 1, inplace = True)

In [9]:
df

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
10836,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [10]:
df["Category"].isnull().sum()

0

In [11]:
df.duplicated().sum()

492

In [12]:
df.drop_duplicates(inplace = True)

In [13]:
df.duplicated().sum()

0

In [14]:
sorted(df["Category"].unique())

['ART_AND_DESIGN',
 'AUTO_AND_VEHICLES',
 'BEAUTY',
 'BOOKS_AND_REFERENCE',
 'BUSINESS',
 'COMICS',
 'COMMUNICATION',
 'DATING',
 'EDUCATION',
 'ENTERTAINMENT',
 'EVENTS',
 'FAMILY',
 'FINANCE',
 'FOOD_AND_DRINK',
 'GAME',
 'HEALTH_AND_FITNESS',
 'HOUSE_AND_HOME',
 'LIBRARIES_AND_DEMO',
 'LIFESTYLE',
 'MAPS_AND_NAVIGATION',
 'MEDICAL',
 'NEWS_AND_MAGAZINES',
 'PARENTING',
 'PERSONALIZATION',
 'PHOTOGRAPHY',
 'PRODUCTIVITY',
 'SHOPPING',
 'SOCIAL',
 'SPORTS',
 'TOOLS',
 'TRAVEL_AND_LOCAL',
 'VIDEO_PLAYERS',
 'WEATHER']

In [15]:
len(df['Category'].unique())

33

In [16]:
# encoding -> Label encoding

In [88]:
from sklearn.preprocessing import LabelEncoder

In [89]:
l_enco = LabelEncoder()

In [19]:
df["Category"] = l_enco.fit_transform(df["Category"])

In [20]:
df

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,0,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,0,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,0,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,0,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,0,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
10836,11,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,11,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,20,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,3,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,18,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

# Why the encoder values are not serial

In [21]:
df["Category"].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 13, 15, 16, 17, 18,
       14, 11, 20, 27, 26, 24, 28, 30, 29, 23, 25, 22, 32, 31, 21, 19])

In [22]:
df.dtypes

Category            int32
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [23]:
df.isna().sum()

Category             0
Rating            1458
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          8
Android Ver          2
dtype: int64

In [24]:
rating_mean = df["Rating"].mean()
rating_mean

4.187885264341964

In [25]:
df["Rating"].fillna(rating_mean, inplace = True)

In [26]:
df["Rating"].isnull().sum()

0

In [27]:
df.isna().sum()

Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              1
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       8
Android Ver       2
dtype: int64

In [28]:
test_mean = df["Rating"].mean()
test_mean

4.187885264341998

In [29]:
df["Reviews"] = df["Reviews"].apply(lambda x: float(x))

In [30]:
df.Reviews.dtypes

dtype('float64')

In [31]:
df_Size = df["Size"].apply(lambda x: x == "Varies with device")

In [32]:
df_Size.sum()

1526

In [35]:
df["Size"] = df["Size"].apply(lambda x: x.replace("Varies with device" , "0M") if x == "Varies with device" else x)

In [36]:
df.loc[10836:10840]

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,11,4.500000,38.0,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,11,5.000000,4.0,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,20,4.187885,3.0,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,3,4.500000,114.0,0M,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,18,4.500000,398307.0,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [37]:
df.loc[10836:10840]

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,11,4.500000,38.0,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,11,5.000000,4.0,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,20,4.187885,3.0,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,3,4.500000,114.0,0M,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,18,4.500000,398307.0,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [38]:
df["Size"] = df["Size"].apply(lambda x: float(x[:-1]))

In [39]:
df.Size.dtypes

dtype('float64')

In [40]:
df["Size"].sum()

329007.9

In [41]:
df.Installs.dtypes

dtype('O')

In [42]:
df["Installs"].replace("[^\d.]", "" , regex=True , inplace = True)

In [48]:
df

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,0,4.100000,159.0,19.0,10000.0,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,0,3.900000,967.0,14.0,500000.0,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,0,4.700000,87510.0,8.7,5000000.0,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,0,4.500000,215644.0,25.0,50000000.0,Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,0,4.300000,967.0,2.8,100000.0,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
10836,11,4.500000,38.0,53.0,5000.0,Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,11,5.000000,4.0,3.6,100.0,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,20,4.187885,3.0,9.5,1000.0,Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,3,4.500000,114.0,0.0,1000.0,Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,18,4.500000,398307.0,19.0,10000000.0,Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [49]:
df["Installs"].dtypes

dtype('float64')

In [50]:
df["Installs"] = df["Installs"].apply(lambda x: float(x))

In [51]:
df["Installs"].unique()

array([1.e+04, 5.e+05, 5.e+06, 5.e+07, 1.e+05, 5.e+04, 1.e+06, 1.e+07,
       5.e+03, 1.e+08, 1.e+09, 1.e+03, 5.e+08, 5.e+01, 1.e+02, 5.e+02,
       1.e+01, 1.e+00, 5.e+00, 0.e+00])

In [52]:
getit = df["Installs"].apply(lambda x: x == "" )

In [53]:
getit.sum()

0

In [54]:
df[df["Installs"] == ""]

Empty DataFrame
Columns: [Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [193]:
df.drop(10472 , axis = 0, inplace = True)

In [195]:
df["Installs"] = df["Installs"].apply(lambda x: float(x))

In [197]:
df.Installs.dtype

dtype('float64')

In [62]:
df.tail()

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,11,4.500000,38.0,53.0,5000.0,0,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,11,5.000000,4.0,3.6,100.0,0,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,20,4.187885,3.0,9.5,1000.0,0,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,3,4.500000,114.0,0.0,1000.0,0,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,18,4.500000,398307.0,19.0,10000000.0,0,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [56]:
df["Type"].unique()

array(['Free', 'Paid', nan], dtype=object)

In [57]:
df[df["Type"].isna()]

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
9148,11,4.187885,0.0,0.0,0.0,NaN,0,Everyone 10+,Strategy,"June 28, 2018",Varies with device,Varies with device

In [58]:
df.drop(9148 , axis = 0, inplace = True)

In [59]:
df["Type"].unique()

array(['Free', 'Paid'], dtype=object)

In [60]:
df["Type"] = l_enco.fit_transform(df["Type"])

In [61]:
df.tail()

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,11,4.500000,38.0,53.0,5000.0,0,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,11,5.000000,4.0,3.6,100.0,0,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,20,4.187885,3.0,9.5,1000.0,0,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,3,4.500000,114.0,0.0,1000.0,0,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,18,4.500000,398307.0,19.0,10000000.0,0,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [63]:
df.Type.dtype

dtype('int32')

In [64]:
df[df["Type"] == 1]

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
234,4,4.700000,11442.0,6.8,100000.0,1,$4.99,Everyone,Business,"March 25, 2018",1.5.2,4.0 and up
235,4,4.800000,10295.0,39.0,100000.0,1,$4.99,Everyone,Business,"April 11, 2017",3.4.6,3.0 and up
427,6,4.000000,18247.0,0.0,100000.0,1,$3.99,Everyone,Communication,"July 5, 2018",7.5.3.20547,4.1 and up
476,7,4.200000,1545.0,0.0,10000.0,1,$3.99,Mature 17+,Dating,"June 19, 2018",2.6.139,4.1 and up
477,7,2.600000,57.0,6.2,1000.0,1,$6.99,Everyone,Dating,"October 25, 2017",1.1.6,4.0 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
10735,11,4.187885,17.0,157.0,100.0,1,$0.99,Mature 17+,Entertainment,"November 25, 2015",1.2,2.1 and up
10760,15,4.400000,35.0,2.4,1000.0,1,$7.99,Everyone,Health & Fitness,"August 8, 2018",1.9.3,4.2 and up
10782,14,3.800000,252.0,11.0,10000.0,1,$16.99,Teen,Action,"February 27, 2015",2.22,5.0 and up
10785,11,4.200000,1405.0,9.5,10000.0,1,$1.20,Everyone,Puzzle,"June 5, 2018",2.7,2.3 and up
10798,11,4.187885,0.0,1020.0,50.0,1,$1.04,Everyone,Puzzle,"February 6, 2012",1.1,3.0 and up

In [65]:
df["Price"].isna().sum()

0

In [66]:
df["Price"].dtype

dtype('O')

In [78]:
df["Price"] = df["Price"].apply(lambda x: x.replace(x[0], "") if x[0] == "$" else x)

In [82]:
df[df["Type"] == 1]

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
234,4,4.700000,11442.0,6.8,100000.0,1,4.99,Everyone,Business,"March 25, 2018",1.5.2,4.0 and up
235,4,4.800000,10295.0,39.0,100000.0,1,4.99,Everyone,Business,"April 11, 2017",3.4.6,3.0 and up
427,6,4.000000,18247.0,0.0,100000.0,1,3.99,Everyone,Communication,"July 5, 2018",7.5.3.20547,4.1 and up
476,7,4.200000,1545.0,0.0,10000.0,1,3.99,Mature 17+,Dating,"June 19, 2018",2.6.139,4.1 and up
477,7,2.600000,57.0,6.2,1000.0,1,6.99,Everyone,Dating,"October 25, 2017",1.1.6,4.0 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
10735,11,4.187885,17.0,157.0,100.0,1,0.99,Mature 17+,Entertainment,"November 25, 2015",1.2,2.1 and up
10760,15,4.400000,35.0,2.4,1000.0,1,7.99,Everyone,Health & Fitness,"August 8, 2018",1.9.3,4.2 and up
10782,14,3.800000,252.0,11.0,10000.0,1,16.99,Teen,Action,"February 27, 2015",2.22,5.0 and up
10785,11,4.200000,1405.0,9.5,10000.0,1,1.20,Everyone,Puzzle,"June 5, 2018",2.7,2.3 and up
10798,11,4.187885,0.0,1020.0,50.0,1,1.04,Everyone,Puzzle,"February 6, 2012",1.1,3.0 and up

In [83]:
df["Price"].loc[234:238]

234    4.99
235    4.99
237       0
238       0
Name: Price, dtype: object

In [84]:
df["Price"].dtype

dtype('O')

In [85]:
df["Price"] = df["Price"].apply(lambda x: float(x))

In [86]:
df.Price.dtype

dtype('float64')

In [87]:
df["Content Rating"].unique()

array(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+',
       'Adults only 18+', 'Unrated'], dtype=object)

In [90]:
df["Content Rating"] = l_enco.fit_transform(df["Content Rating"])

In [91]:
df["Content Rating"].unique()

array([1, 4, 2, 3, 0, 5])

In [92]:
df

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,0,4.100000,159.0,19.0,10000.0,0,0.0,1,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,0,3.900000,967.0,14.0,500000.0,0,0.0,1,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,0,4.700000,87510.0,8.7,5000000.0,0,0.0,1,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,0,4.500000,215644.0,25.0,50000000.0,0,0.0,4,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,0,4.300000,967.0,2.8,100000.0,0,0.0,1,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
10836,11,4.500000,38.0,53.0,5000.0,0,0.0,1,Education,"July 25, 2017",1.48,4.1 and up
10837,11,5.000000,4.0,3.6,100.0,0,0.0,1,Education,"July 6, 2018",1.0,4.1 and up
10838,20,4.187885,3.0,9.5,1000.0,0,0.0,1,Medical,"January 20, 2017",1.0,2.2 and up
10839,3,4.500000,114.0,0.0,1000.0,0,0.0,3,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,18,4.500000,398307.0,19.0,10000000.0,0,0.0,1,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [94]:
sorted(df["Genres"].unique())

['Action',
 'Action;Action & Adventure',
 'Adventure',
 'Adventure;Action & Adventure',
 'Adventure;Brain Games',
 'Adventure;Education',
 'Arcade',
 'Arcade;Action & Adventure',
 'Arcade;Pretend Play',
 'Art & Design',
 'Art & Design;Action & Adventure',
 'Art & Design;Creativity',
 'Art & Design;Pretend Play',
 'Auto & Vehicles',
 'Beauty',
 'Board',
 'Board;Action & Adventure',
 'Board;Brain Games',
 'Board;Pretend Play',
 'Books & Reference',
 'Books & Reference;Creativity',
 'Books & Reference;Education',
 'Business',
 'Card',
 'Card;Action & Adventure',
 'Card;Brain Games',
 'Casino',
 'Casual',
 'Casual;Action & Adventure',
 'Casual;Brain Games',
 'Casual;Creativity',
 'Casual;Education',
 'Casual;Music & Video',
 'Casual;Pretend Play',
 'Comics',
 'Comics;Creativity',
 'Communication',
 'Communication;Creativity',
 'Dating',
 'Education',
 'Education;Action & Adventure',
 'Education;Brain Games',
 'Education;Creativity',
 'Education;Education',
 'Education;Music & Video',
 'Education;Pretend Play',
 'Educational',
 'Educational;Action & Adventure',
 'Educational;Brain Games',
 'Educational;Creativity',
 'Educational;Education',
 'Educational;Pretend Play',
 'Entertainment',
 'Entertainment;Action & Adventure',
 'Entertainment;Brain Games',
 'Entertainment;Creativity',
 'Entertainment;Education',
 'Entertainment;Music & Video',
 'Entertainment;Pretend Play',
 'Events',
 'Finance',
 'Food & Drink',
 'Health & Fitness',
 'Health & Fitness;Action & Adventure',
 'Health & Fitness;Education',
 'House & Home',
 'Libraries & Demo',
 'Lifestyle',
 'Lifestyle;Education',
 'Lifestyle;Pretend Play',
 'Maps & Navigation',
 'Medical',
 'Music',
 'Music & Audio;Music & Video',
 'Music;Music & Video',
 'News & Magazines',
 'Parenting',
 'Parenting;Brain Games',
 'Parenting;Education',
 'Parenting;Music & Video',
 'Personalization',
 'Photography',
 'Productivity',
 'Puzzle',
 'Puzzle;Action & Adventure',
 'Puzzle;Brain Games',
 'Puzzle;Creativity',
 'Puzzle;Education',
 'Racing',
 'Racing;Action & Adventure',
 'Racing;Pretend Play',
 'Role Playing',
 'Role Playing;Action & Adventure',
 'Role Playing;Brain Games',
 'Role Playing;Education',
 'Role Playing;Pretend Play',
 'Shopping',
 'Simulation',
 'Simulation;Action & Adventure',
 'Simulation;Education',
 'Simulation;Pretend Play',
 'Social',
 'Sports',
 'Sports;Action & Adventure',
 'Strategy',
 'Strategy;Action & Adventure',
 'Strategy;Creativity',
 'Strategy;Education',
 'Tools',
 'Tools;Education',
 'Travel & Local',
 'Travel & Local;Action & Adventure',
 'Trivia',
 'Trivia;Education',
 'Video Players & Editors',
 'Video Players & Editors;Creativity',
 'Video Players & Editors;Music & Video',
 'Weather',
 'Word']

In [95]:
len(df["Genres"].unique())

119

In [96]:
df["Genres"] = l_enco.fit_transform(df["Genres"])

In [97]:
df

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,0,4.100000,159.0,19.0,10000.0,0,0.0,1,9,"January 7, 2018",1.0.0,4.0.3 and up
1,0,3.900000,967.0,14.0,500000.0,0,0.0,1,12,"January 15, 2018",2.0.0,4.0.3 and up
2,0,4.700000,87510.0,8.7,5000000.0,0,0.0,1,9,"August 1, 2018",1.2.4,4.0.3 and up
3,0,4.500000,215644.0,25.0,50000000.0,0,0.0,4,9,"June 8, 2018",Varies with device,4.2 and up
4,0,4.300000,967.0,2.8,100000.0,0,0.0,1,11,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
10836,11,4.500000,38.0,53.0,5000.0,0,0.0,1,39,"July 25, 2017",1.48,4.1 and up
10837,11,5.000000,4.0,3.6,100.0,0,0.0,1,39,"July 6, 2018",1.0,4.1 and up
10838,20,4.187885,3.0,9.5,1000.0,0,0.0,1,71,"January 20, 2017",1.0,2.2 and up
10839,3,4.500000,114.0,0.0,1000.0,0,0.0,3,19,"January 19, 2015",Varies with device,Varies with device
10840,18,4.500000,398307.0,19.0,10000000.0,0,0.0,1,67,"July 25, 2018",Varies with device,Varies with device

In [99]:
ll = ["4" , "5" , "6" , "7" , "8" , "9" , "10" , "20"]

In [102]:
mm = ll[-4:]
mm

['8', '9', '10', '20']

In [103]:
df["Last Updated"] = df["Last Updated"].apply(lambda x: x.replace(x , x[-4:]))

In [105]:
df["Last Updated"] = df["Last Updated"].apply(lambda x: float(x))

In [106]:
df["Last Updated"].dtype

dtype('float64')

In [108]:
df["Last Updated"] = df["Last Updated"].apply(lambda x: int(x))

In [109]:
df

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,0,4.100000,159.0,19.0,10000.0,0,0.0,1,9,2018,1.0.0,4.0.3 and up
1,0,3.900000,967.0,14.0,500000.0,0,0.0,1,12,2018,2.0.0,4.0.3 and up
2,0,4.700000,87510.0,8.7,5000000.0,0,0.0,1,9,2018,1.2.4,4.0.3 and up
3,0,4.500000,215644.0,25.0,50000000.0,0,0.0,4,9,2018,Varies with device,4.2 and up
4,0,4.300000,967.0,2.8,100000.0,0,0.0,1,11,2018,1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
10836,11,4.500000,38.0,53.0,5000.0,0,0.0,1,39,2017,1.48,4.1 and up
10837,11,5.000000,4.0,3.6,100.0,0,0.0,1,39,2018,1.0,4.1 and up
10838,20,4.187885,3.0,9.5,1000.0,0,0.0,1,71,2017,1.0,2.2 and up
10839,3,4.500000,114.0,0.0,1000.0,0,0.0,3,19,2015,Varies with device,Varies with device
10840,18,4.500000,398307.0,19.0,10000000.0,0,0.0,1,67,2018,Varies with device,Varies with device

In [110]:
df["Last Updated"].dtype

dtype('int64')